# TODO: add deployment workflow, examples
# https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/gae/.github/workflows/app-engine.yml
# https://github.com/marketplace/actions/setup-gcloud-environment

name: Build & Test

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [8.x, 10.x, 12.x]
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      #  all installs
      # - name: install deps for ./pokemon-app
      #   run: npm install
      #   working-directory: ./pokemon-app
      - name: install deps for ./api
        run: npm install & npm i -g tsoa js-yaml typescript @angular/cli mocha ts-node @types/chai @types/mocha
        working-directory: ./api

      # server API
      - uses: actions/checkout@v2
      - name: Decrypt secrets
        run: sh scripts/decrypt-secrets.sh $POKEMON_PASSPHRASE     
        env:
          POKEMON_PASSPHRASE: ${{ secrets.POKEMON_PASSPHRASE }}
          db_uri: ${{ secrets.DB_URI }}
          GOOGLE_APPLICATION_CREDENTIALS: ~/secrets/service-account.json
          # cicd: githubaction
          build: dev
          firebase_database_url: https://pokemon-dcb38.firebaseio.com
        working-directory: ./api
      # - name: Test printing your secret (Remove this step in production)
      #   run: cat $HOME/secrets/dev.env
        # working-directory: ./api
      - uses: actions/checkout@v2
      - name: Run api server tests
        run: npm test
        working-directory: ./api

      # web ui
      # NOTE: Run this last since it takes the longest
      - name: build portal
        run: npm run build --if-present
        working-directory: ./app-pokemon
    # https://intuit.github.io/auto/pages/getting-started.html
