# TODO: add deployment workflow, examples
# https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/gae/.github/workflows/app-engine.yml
# https://github.com/marketplace/actions/setup-gcloud-environment

name: Build & Test

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [8.x, 10.x, 12.x]
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: install deps for ./api
        with:
          node-version: ${{ matrix.node-version }}  
        env:
          POKEMON_PASSPHRASE: ${{ secrets.POKEMON_PASSPHRASE }}
          cicd: githubaction
          build: dev
        run: npm install & npm i -g tsoa js-yaml typescript @angular/cli mocha ts-node
        working-directory: ./api
        
      # server API
      - name: Decrypt secrets
        run: sh scripts/decrypt-secrets.sh $POKEMON_PASSPHRASE     
        working-directory: ./api
        
      # - name: Test printing your secret (Remove this step in production)
      #   run: cat $HOME/secrets/dev.env
        # working-directory: ./api
      - name: Run api server tests
        run: npm test
        working-directory: ./api

      # web ui
      # NOTE: Run this last since it takes the longest
      - name: build portal
        run: npm run build --if-present
        working-directory: ./app-pokemon
    # https://intuit.github.io/auto/pages/getting-started.html
